config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

  root 'application#hello'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text:"Hello! World."
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time=Time.now
    @files=Dir.glob('*')
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OVO</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Good Bye</h1>
<p>It's nice to have you here.</p>
<br/><br/>
Say <%= link_to "Hello",say_hello_path %> Again.

app/views/say/hello.html.erb
<h1>Hello from Rails</h1>
<p>
  It is now <%= @time %><br/><br/>
  Time to say <%= link_to "Goodbye",say_goodbye_path %>.
</p>

<h3><%= 1+2 %></h3>
<h3><%= "cow"+"down" %></h3>
<h3><%= 1.hour.from_now.localtime %></h3>

<ul>
  <% for file in  @files %>
   <li>  <%= file %></li>
  <% end %>
</ul>